# Generated by Django 5.0.1 on 2024-04-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
